# Basic
title: LJ’Blog
subtitle: Valar Morghulis Valar Dohaeris 
welcome_message: <a href="https://github.com/JonSir/” target="_blank"></a>
description: smile and live a good life .
creator: <a href="http://onev.cat">@onevcat</a>

url: "https://github.com/JonSir/"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 鼻涕虫匹诺曹
    github:  jonsir
    twitter: Johnny_The_D
    gplus: 107108267983477358170
    mail: ljduan2013@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
