# Basic
title: manajay
subtitle: Valar Morghulis Valar Dohaeris

#welcome_message: <a href="https://github.com/manajay/" target="_blank">拥抱开源,在 Github</a>

#disqus_url
url: "https://www.manajay.com"

description: 静下心来,用心观察 处处都透着生活的美.

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: gray

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 最近更新

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}  


# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: manajay
    #provider : duoshuo
    #duoshuo :
    #short_name : manajay
    
# Social
social:
    weibo: Manajay_dlj
    github: manajay
    twitter: manajay_dlj
    mail: manajay.dlj@gmail.com

