# Basic
title: Mana Jay’Blog
subtitle: Valar Morghulis Valar Dohaeris

#welcome_message: <a href="https://github.com/manajay/" target="_blank">求知,在 Github</a>

description: 静下心来,用心观察 处处都透着生活的美.

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: gray

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客


# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: manajay
    # duoshuo: 
    
# Social
social:
    github: manajay
    twitter: Johnny_The_D
    mail: manajay.dlj@gmail.com

